spring.application.name=patient-service

server.port=4000

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/patientManagement
spring.datasource.username=postgres
spring.datasource.password=root

# Hibernate (JPA) properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
